server:
  port: 9000
spring:
  application:
    name: event-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/event-manager
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: "Munashe056"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"
